language: java
dist: xenial
jdk:
  - oraclejdk11
before_install:
  - chmod +x maybe-release.sh
  # install groovy
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install groovy 3.0.8
  - echo $(groovy --version)
install:
    - mvn install -Dmaven.javadoc.skip=true -B -V
before_script:
  - git config --global user.email "swisspush@post.ch"
  - git config --global user.name "Travis-CI"
script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - ./maybe-release.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
